# Generated by Django 3.2.3 on 2021-07-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='descriptions',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='urls',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='imagess',
            field=models.ImageField(default=False, upload_to='image'),
        ),
    ]
